export const BREAK_INCREASE = 'BREAK_INCREASE';
export const BREAK_DECREASE = 'BREAK_DECREASE';
export const SESSION_INCREASE = 'SESSION_INCREASE';
export const SESSION_DECREASE = 'SESSION_DECREASE';
export const SET_CURRENT_TIME = 'SET_CURRENT_TIME';
